# COMP47670 Assignment 1 - Autumn 2026/27
## Task 2: Data Preprocessing

**Student Name**: Ellen Lyons

**Student Number**: 26117753

In [67]:
import pandas as pd

df_raw = pd.read_csv("property-sale-register.csv")
df_raw.head()

,Property Details,First Time Buyer,Size,Garage,Garden,Sale Price,Date Sold,Year Built,Location,Property Reference
0,Type: Detached; Style: 1.5-Storey; 3 Bedrooms;...,Yes,"1,131sqft",Yes,Yes,"€359,086.00",Sold 26 December 2022,1984,Oak Park,PROP-105204
1,Type: Detached; 2 Bathrooms; Style: 2-Storey; ...,NO,"1,941sqft",Yes,Yes,"€734,419.00",Sold 2022-12-25,2019,Porter Square,PROP-105203
2,Type: Det.; Style: 2-Storey; 3 Bedrooms; 2 Bat...,No,"1,996 sqft",Yes,Yes,"€724,835.00",Sold 2022-12-19,2021,Porter Square,PROP-105202
3,Type: Detached; Style: 1.5-Storey; 3 Bedrooms;...,No,"1,463sqft",Yes,Yes,"€446,404.00",Sold 2022-12-18,2013,Avoca,PROP-105201
4,Type: Detached; Style: 2-Storey; 3 Bedrooms; 2...,No,"1,660 sq ft",Yes,Yes,"€554,762.00",Sold 2022-12-17,2008,Brookville,PROP-105200

In [68]:
# check that there is a different property reference for each listing
unique_IDs = df_raw["Property Reference"].unique()

# if the number of rows = the number of property IDs, then we can use this as the index
if len(unique_IDs) == df.shape[0]:
    print("There is a unique property reference for every property")

There is a unique property reference for every property

In [69]:
df = df_raw.copy()

# lets use property ref as the index column 
df = df.set_index("Property Reference")
df.head()

,Property Details,First Time Buyer,Size,Garage,Garden,Sale Price,Date Sold,Year Built,Location
Property Reference,,,,,,,,,
PROP-105204,Type: Detached; Style: 1.5-Storey; 3 Bedrooms;...,Yes,"1,131sqft",Yes,Yes,"€359,086.00",Sold 26 December 2022,1984,Oak Park
PROP-105203,Type: Detached; 2 Bathrooms; Style: 2-Storey; ...,NO,"1,941sqft",Yes,Yes,"€734,419.00",Sold 2022-12-25,2019,Porter Square
PROP-105202,Type: Det.; Style: 2-Storey; 3 Bedrooms; 2 Bat...,No,"1,996 sqft",Yes,Yes,"€724,835.00",Sold 2022-12-19,2021,Porter Square
PROP-105201,Type: Detached; Style: 1.5-Storey; 3 Bedrooms;...,No,"1,463sqft",Yes,Yes,"€446,404.00",Sold 2022-12-18,2013,Avoca
PROP-105200,Type: Detached; Style: 2-Storey; 3 Bedrooms; 2...,No,"1,660 sq ft",Yes,Yes,"€554,762.00",Sold 2022-12-17,2008,Brookville

In [70]:
print(df["First Time Buyer"].unique())
print(df["Garage"].unique())
print(df["Garden"].unique())

<StringArray>
['Yes', 'NO', 'No', 'YES']
Length: 4, dtype: str
<StringArray>
['Yes', 'No', '???']
Length: 3, dtype: str
<StringArray>
['Yes', '???', 'No']
Length: 3, dtype: str

In [71]:
df["First Time Buyer"] = df["First Time Buyer"].replace({"NO" : "No", "YES": "Yes"})
print(df["First Time Buyer"].unique())

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [ ]:
# treat blank entries and unknown markers as missing
missing_markers = {"", "???", "Unknown"}

print("Missing values per feature:")
for feature in feature_names:
    missing_count = 0
    for row in restaurants:
        if row[feature].strip() in missing_markers:
            missing_count += 1
    print(f"  {feature:<22} {missing_count}")